<a href="https://colab.research.google.com/github/P3344828/Anomaly-/blob/main/Text_generation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment Code: DS-AG-031
# Generative AI - Text Generation and Machine Translation | Assignment

**Q1.** What is Generative AI and what are its primary use cases across industries?

- **Ans: Generative Artificial Intelligence (Generative AI)** is a type of AI that generates new and original content-such as text, images, audio, code, or data-by learning patterns from existing datasets. Unlike traditional AI, it focuses on content creation rather than prediction or classification.

- It is widely used across industries for automated content generation, software development, healthcare research, financial reporting, marketing personalization, education, and customer support, improving efficiency, innovation, and decision-making.

**Q2.** Explain the role of probabilistic modeling in generative models. How do these models differ from discriminative models?

- **Ans: Probabilistic modeling** enables generative models to learn the underlying probability distribution of data, allowing them to generate new and realistic samples by capturing uncertainty and variability. These models typically learn the joint or marginal data distribution.

- In contrast, **discriminative models** learn the conditional probability of outputs given inputs and focus solely on prediction or classification. While generative models can create new data, discriminative models are optimized only for accurate decision-making.

**Q3.** What is the difference between Autoencoders and Variational Autoencoders (VAEs) in the context of text generation?

- **Ans: Autoencoders** learn a deterministic latent representation of text, where each input is mapped to a single fixed vector and then reconstructed. They are effective for feature learning and reconstruction tasks, but their latent space is not structured or continuous, which limits their ability to generate diverse or novel text beyong the training data.

- **Variational Autoencoders (VAEs)**, on the other hand, use a probabilistic latent space by learning a distribution (mean and variance) for each input. This structured and continuous latent space allows sampling and smooth interpolation, enabling VAEs to generate new, coherent, ad diverse text outputs, making them more suitable for text generation tasks.

**Q4.** Describe the working of attention mechanisms in Neural Machine Translation (NMT). Why are they critical?

- **Ans:** The **attention mechanism** in Neural Machine Translation enables the decoder to dynamically focus on the most relevant parts of the source sentence while generating each target word.

- Instead of compressing the entire source sentence into a single fixed-length vector, the encoder produces a sequence of hidden states. At each decoding step, the decoder computes attention scores between its current hidden state and all encoder hidden states. These scores are normalized to obtain attention weights, which are used to form a context vector as a weighted sum of encoder states. This context vector, combined with the decoder state, is used to predict the next target word.

- ** Importance of Attention in NMT:**
  - Eliminates the fixed-length context bottleneck.
  - Improves handling of long and complex sentences.
  - Learns soft alignments between source and target words.
  - Significantly enhances translation accuracy and fluency.

**Q5.** What ethical considerations must be addressed when using generative AI for creative content such as poetry or storytelling?

- **Ans: Ethical considerations in using generative AI for creative content:**
- Generative AI must be used with transparency, clearly acknowledging AI involvement in authorship. It should respect copyright and originality, avoiding plagiarism or replication of protected works. Models must address bias and fairness to prevent harmful or stereotypical content, ensure cultural sensitivity, and avoid generating misleading or harmful narratives. Ethical use also requires responsible handling of training data and consent.

**Q10.** Imagine you are building a creative writing assistant for a publishing
company. The assistant should generate story plots and character descriptions using Generative AI. Describe how you would design the system, including model selection, training data, bias mitigation, and evaluation methods. Explain the real-world challenges you might face.

- **Ans:** A creative writing assistant for a publishing company can be designed using Generative Artificial Intelligence to automatically generate story plots and detailed character descriptions. The system should support creativity while ensuring originality, ethical responsibility, and editorial control.

- **Model Selection:** The assistant would be built using a large pre-trained language model (LLM), such as an instruction-tuned GPT-style model, due to its strong ability to understand narrative structure and generate coherent, long-form creative text. Fine-tuning or prompt engineering can be applied to adapt the model to the publishing company’s preferred writing style and genres.

- **Training Data:** Training data would include high-quality and legally sourced literary content, such as licensed novels, short stories, public-domain literature, and internal editorial guidelines. The data would be cleaned, annotated, and balanced across genres, themes, and character types to improve generalization and creativity.

- **Bias Mitigation:** To reduce bias, the system would use diverse and representative datasets, along with automated bias and toxicity detection tools. Additionally, a human-in-the-loop review process would be implemented to identify and correct biased or inappropriate outputs before publication.

- **Evaluation Methods:** Evaluation would involve both automatic and human-based methods. Automatic evaluation would assess fluency, coherence, and lexical diversity, while human editors would evaluate creativity, originality, narrative consistency, and audience suitability. User feedback can further improve the system over time.

- **Real-World Challenges:** Key challenges include ensuring originality and avoiding plagiarism, managing subjective aspects of creativity, mitigating hidden biases, maintaining consistent narrative flow, and handling the high computational cost of large language models.


**Q6.** Use the following small text dataset to train a simple Variational Autoencoder (VAE) for text reconstruction:

["The sky is blue", "The sun is bright", "The grass is green",
"The night is dark", "The stars are shining"]

 1. Preprocess the data (tokenize and pad the sequences).
 2. Build a basic VAE model for text reconstruction.
 3. Train the model and show how it reconstructs or generates similar sentences.

  Include your code, explanation, and sample outputs.

- **Ans:** 1. Data Preprocessing (Tokenization & Padding):
  - Text data is converted into numerical form using tokenization. All sequences are padded to the same length so they can be fed into a neural network.

- 2. Building a Simple VAE Model:
   - The encoder compresses the input sentence into a latent vector.
   - The latent space uses mean and variance (VAE concept).
   - The decoder reconstructs the original sentence from the latent vector.

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Input, Embedding, LSTM, Dense, Lambda, RepeatVector, TimeDistributed, Layer # Import Layer
from tensorflow.keras.models import Model
from tensorflow.keras import backend as K

# Dataset
sentences = [
    "The sky is blue",
    "The sun is bright",
    "The grass is green",
    "The night is dark",
    "The stars are shining"
]

# Tokenize
tokenizer = Tokenizer(lower=True)
tokenizer.fit_on_texts(sentences)
sequences = tokenizer.texts_to_sequences(sentences)

# Vocabulary size
vocab_size = len(tokenizer.word_index) + 1

# Padding
max_len = max(len(seq) for seq in sequences)
X = pad_sequences(sequences, maxlen=max_len, padding='post')

print("Vocabulary size:", vocab_size)
print("Padded sequences:\n", X)

# Parameters
embedding_dim = 16
latent_dim = 8

# Encoder
encoder_inputs = Input(shape=(max_len,))
x = Embedding(vocab_size, embedding_dim, mask_zero=True)(encoder_inputs)
h = LSTM(32)(x)

z_mean = Dense(latent_dim)(h)
z_log_var = Dense(latent_dim)(h)

def sampling(args):
    z_mean, z_log_var = args
    epsilon = K.random_normal(shape=(K.shape(z_mean)[0], latent_dim))
    return z_mean + K.exp(0.5 * z_log_var) * epsilon

z = Lambda(sampling)([z_mean, z_log_var])

# Custom KL Divergence Layer
class KLDivergenceLayer(Layer):
    def __init__(self, **kwargs):
        super(KLDivergenceLayer, self).__init__(**kwargs)

    def call(self, inputs):
        z_mean_val, z_log_var_val = inputs
        kl_loss_per_sample = -0.5 * K.sum(
            1 + z_log_var_val - K.square(z_mean_val) - K.exp(z_log_var_val), axis=1
        )
        self.add_loss(K.mean(kl_loss_per_sample)) # Add the mean KL loss to the model
        return inputs # Pass through the inputs (or any tensor needed downstream)

# Add the KL Divergence Layer to the model graph
# This layer doesn't change the tensor, but registers the KL loss
_ = KLDivergenceLayer(name='kl_divergence_loss_layer')([z_mean, z_log_var])


# Decoder
decoder_h = RepeatVector(max_len)(z)
decoder_h = LSTM(32, return_sequences=True)(decoder_h)
decoder_outputs = TimeDistributed(Dense(vocab_size, activation='softmax'))(decoder_h)

# VAE Model
vae = Model(encoder_inputs, decoder_outputs)

# Compile with only reconstruction loss (KL is handled by custom layer)
vae.compile(optimizer='adam', loss='sparse_categorical_crossentropy')
vae.summary()

# Train
vae.fit(
    X, X,   # X as both input and target. y_true shape (batch_size, max_len)
            # is compatible with y_pred shape (batch_size, max_len, vocab_size) for sparse_categorical_crossentropy
    epochs=200,
    batch_size=2,
    verbose=0
)

# Decode predictions
def decode_sequence(pred):
    words = []
    for token in np.argmax(pred, axis=-1):
        if token != 0:
            words.append(tokenizer.index_word[token])
    return " ".join(words)

reconstructions = vae.predict(X)

for original, recon in zip(sentences, reconstructions):
    print("Original:     ", original)
    print("Reconstructed:", decode_sequence(recon))
    print()


Vocabulary size: 14
Padded sequences:
 [[ 1  3  2  4]
 [ 1  5  2  6]
 [ 1  7  2  8]
 [ 1  9  2 10]
 [ 1 11 12 13]]


Model: "functional_4"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_6       │ (None, 4)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding_6         │ (None, 4, 16)     │        224 │ input_layer_6[0]… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ not_equal_2         │ (None, 4)         │          0 │ input_layer_6[0]… │
│ (NotEqual)          │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ lstm_8 (LSTM)       │ (None, 32)        │      6,272 │ embedding_6[0][0… │
│                     │                   │            │ not_equal_2[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_8 (Dense)     │ (None, 8)         │        264 │ lstm_8[0][0]      │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_9 (Dense)     │ (None, 8)         │        264 │ lstm_8[0][0]      │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ lambda_2 (Lambda)   │ (None, 8)         │          0 │ dense_8[0][0],    │
│                     │                   │            │ dense_9[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ repeat_vector_2     │ (None, 4, 8)      │          0 │ lambda_2[0][0]    │
│ (RepeatVector)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ lstm_9 (LSTM)       │ (None, 4, 32)     │      5,248 │ repeat_vector_2[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ time_distributed_2  │ (None, 4, 14)     │        462 │ lstm_9[0][0]      │
│ (TimeDistributed)   │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 12,734 (49.74 KB)

 Trainable params: 12,734 (49.74 KB)

 Non-trainable params: 0 (0.00 B)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 492ms/step
Original:      The sky is blue
Reconstructed: the sky is blue

Original:      The sun is bright
Reconstructed: the night is bright

Original:      The grass is green
Reconstructed: the grass is green

Original:      The night is dark
Reconstructed: the night is bright

Original:      The stars are shining
Reconstructed: the stars are shining



**Q7.** Use a pre-trained GPT model (like GPT-2 or GPT-3) to translate a short
English paragraph into French and German. Provide the original and translated text.

In [ ]:
# Install transformers if not already installed
# !pip install transformers

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# Original English text
text = """Artificial intelligence is transforming the way we live and work.
It helps us analyze data, make better decisions, and even create art.
The future will be shaped by how responsibly we use this powerful technology."""

# Load models and tokenizers explicitly
model_name_fr = "Helsinki-NLP/opus-mt-en-fr"
tokenizer_fr = AutoTokenizer.from_pretrained(model_name_fr)
model_fr = AutoModelForSeq2SeqLM.from_pretrained(model_name_fr)

model_name_de = "Helsinki-NLP/opus-mt-en-de"
tokenizer_de = AutoTokenizer.from_pretrained(model_name_de)
model_de = AutoModelForSeq2SeqLM.from_pretrained(model_name_de)

# Translate to French
inputs_fr = tokenizer_fr(text, return_tensors="pt", padding=True)
translated_tokens_fr = model_fr.generate(**inputs_fr, max_length=200)
translation_fr = tokenizer_fr.decode(translated_tokens_fr[0], skip_special_tokens=True)

# Translate to German
inputs_de = tokenizer_de(text, return_tensors="pt", padding=True)
translated_tokens_de = model_de.generate(**inputs_de, max_length=200)
translation_de = tokenizer_de.decode(translated_tokens_de[0], skip_special_tokens=True)

print("Original (English):\n", text)
print("\nFrench Translation:\n", translation_fr)
print("\nGerman Translation:\n", translation_de)


Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

**Q8.** Implement a simple attention-based encoder-decoder model for English-to-Spanish translation using Tensorflow or PyTorch.

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding, LSTM, Dense, Input, Dot, Activation, Concatenate


# Dataset

pairs = [
    ("hello", "hola"),
    ("how are you", "como estas"),
    ("good morning", "buenos dias"),
    ("thank you", "gracias"),
    ("good night", "buenas noches")
]

eng_texts, spa_texts = zip(*pairs)


# Tokenization

eng_tokenizer = Tokenizer(lower=True)
spa_tokenizer = Tokenizer(lower=True)

eng_tokenizer.fit_on_texts(eng_texts)
spa_tokenizer.fit_on_texts(spa_texts)

eng_seqs = eng_tokenizer.texts_to_sequences(eng_texts)
spa_seqs = spa_tokenizer.texts_to_sequences(spa_texts)

max_eng_len = max(len(s) for s in eng_seqs)
max_spa_len = max(len(s) for s in spa_seqs)

eng_vocab_size = len(eng_tokenizer.word_index) + 1
spa_vocab_size = len(spa_tokenizer.word_index) + 1

encoder_input_data = pad_sequences(eng_seqs, maxlen=max_eng_len, padding='post')
decoder_input_data = pad_sequences(spa_seqs, maxlen=max_spa_len, padding='post')


# Model Parameters

latent_dim = 64


#  Encoder

encoder_inputs = Input(shape=(max_eng_len,))
enc_emb = Embedding(eng_vocab_size, latent_dim)(encoder_inputs)
encoder_lstm = LSTM(latent_dim, return_sequences=True, return_state=True)
encoder_outputs, state_h, state_c = encoder_lstm(enc_emb)


#  Decoder

decoder_inputs = Input(shape=(max_spa_len,))
dec_emb = Embedding(spa_vocab_size, latent_dim)(decoder_inputs)
decoder_lstm = LSTM(latent_dim, return_sequences=True, return_state=True)
decoder_outputs, _, _ = decoder_lstm(
    dec_emb, initial_state=[state_h, state_c]
)


#  Attention

attention = Dot(axes=[2, 2])([decoder_outputs, encoder_outputs])
attention = Activation('softmax')(attention)
context = Dot(axes=[2, 1])([attention, encoder_outputs])

decoder_combined_context = Concatenate(axis=-1)(
    [context, decoder_outputs]
)


#  Output Layer

output = Dense(spa_vocab_size, activation="softmax")(
    decoder_combined_context
)

model = tf.keras.Model(
    [encoder_inputs, decoder_inputs],
    output
)

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy"
)

model.summary()


#  Training

decoder_target_data = np.expand_dims(decoder_input_data, -1)

model.fit(
    [encoder_input_data, decoder_input_data],
    decoder_target_data,
    batch_size=2,
    epochs=300,
    verbose=0
)


# Translation Function (FIXED)

def translate_sentence(sentence):
    seq = eng_tokenizer.texts_to_sequences([sentence])
    seq = pad_sequences(seq, maxlen=max_eng_len, padding='post')

    dummy_decoder_input = np.zeros((1, max_spa_len))

    prediction = model.predict([seq, dummy_decoder_input], verbose=0)
    tokens = np.argmax(prediction[0], axis=-1)

    words = [
        spa_tokenizer.index_word.get(t, "")
        for t in tokens if t != 0
    ]

    return " ".join(words)


#  Test

print("English: hello -> Spanish:", translate_sentence("hello"))
print("English: good night -> Spanish:", translate_sentence("good night"))

Model: "functional_3"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_4       │ (None, 3)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ input_layer_5       │ (None, 2)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding_4         │ (None, 3, 64)     │        576 │ input_layer_4[0]… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding_5         │ (None, 2, 64)     │        576 │ input_layer_5[0]… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ lstm_6 (LSTM)       │ [(None, 3, 64),   │     33,024 │ embedding_4[0][0] │
│                     │ (None, 64),       │            │                   │
│                     │ (None, 64)]       │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ lstm_7 (LSTM)       │ [(None, 2, 64),   │     33,024 │ embedding_5[0][0… │
│                     │ (None, 64),       │            │ lstm_6[0][1],     │
│                     │ (None, 64)]       │            │ lstm_6[0][2]      │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dot_2 (Dot)         │ (None, 2, 3)      │          0 │ lstm_7[0][0],     │
│                     │                   │            │ lstm_6[0][0]      │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_1        │ (None, 2, 3)      │          0 │ dot_2[0][0]       │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dot_3 (Dot)         │ (None, 2, 64)     │          0 │ activation_1[0][… │
│                     │                   │            │ lstm_6[0][0]      │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate_1       │ (None, 2, 128)    │          0 │ dot_3[0][0],      │
│ (Concatenate)       │                   │            │ lstm_7[0][0]      │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_7 (Dense)     │ (None, 2, 9)      │      1,161 │ concatenate_1[0]… │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 68,361 (267.04 KB)

 Trainable params: 68,361 (267.04 KB)

 Non-trainable params: 0 (0.00 B)

English: hello -> Spanish: hola
English: good night -> Spanish: buenas noches


**Q9.** Use the following short poetry dataset to simulate poem generation with a pre-trained GPT model:
 ["Roses are red, violets are blue,", "Sugar is sweet, and so are you.",
  "The moon glows bright in silent skies,", "A bird sings where the soft wind sighs."]

 Using this dataset as a reference for poetic structure and language, generate a new 2-4 line poem using a pre-trained GPT model (such as GPT-2). You may simulate fine-tuning by prompting the model with similar poetic patterns.

Include your code, the prompt used, and the generated poem in your answer.

In [ ]:
# Install transformers if not already installed
#!pip install transformers

from transformers import pipeline, set_seed

# Load GPT-2 text generation pipeline
generator = pipeline("text-generation", model="gpt2")
set_seed(42)

# Prompt: simulate fine-tuning by giving poetic examples
prompt = """Roses are red, violets are blue,
Sugar is sweet, and so are you.
The moon glows bright in silent skies,
A bird sings where the soft wind sighs.

Now write a new short poem:"""

# Generate poem with improved sampling
poem = generator(
    prompt,
    max_new_tokens=60,        # number of tokens to generate
    num_return_sequences=1,
    temperature=0.7,          # creativity control
    top_k=50,                 # restrict to top 50 tokens
    top_p=0.9,                # nucleus sampling
    do_sample=True            # enable sampling
)[0]['generated_text']

print("Prompt:\n", prompt)
print("\nGenerated Poem:\n", poem)

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: gpt2
Key                  | Status     |  | 
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=60) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


Prompt:
 Roses are red, violets are blue,
Sugar is sweet, and so are you.
The moon glows bright in silent skies,
A bird sings where the soft wind sighs.

Now write a new short poem:

Generated Poem:
 Roses are red, violets are blue,
Sugar is sweet, and so are you.
The moon glows bright in silent skies,
A bird sings where the soft wind sighs.

Now write a new short poem:

For a long time I thought that my life was to die,

But now my life is to be reborn.

And now I am reborn!

And now I am reborn!

Now write a new short poem:

For a long time I thought that
